### ISSUE TITLE
appVersion type error in Chart.yaml

### ISSUE THREAD

**Issue by matthias4217** [vidispine/hull#169]
Helm lint (Helm version `3.10.0`, `3.8.2`, `3.5.0`) gives the following :
```sh
$ helm lint .
==> Linting .
[ERROR] Chart.yaml: appVersion should be of type string but it's of type float64
[INFO] Chart.yaml: icon is recommended

Error: 1 chart(s) linted, 1 chart(s) failed
```

Indeed in [Chart.yaml](https://github.com/vidispine/hull/blob/main/hull/Chart.yaml), we've got `appVersion: 1.25`. The value should be quoted, as it is currently interpreted as a float.

This is quite a minor detail, but it may break workflows relying on linting to check the validity of the chart.

**Comment by gre9ory** [comment]
Thanks for that! I intend to repair it and close the issue with the next set of releases coming soon!
